[package]
name = "polaris_plant"
version = "0.1.0"
edition = "2021"

[dependencies]
altai-rs = { path = "../altai-rs" }
polaris_fsw = { path = "../polaris_fsw" }
ndarray = "0.16.1"
polaris_log = { path = "../polaris_log" }
